pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = plugin_manager.pc
EXTRA_DIST = $(pkgconfig_DATA)

if BUILDSYSTEM_OPENWRT
AM_CPPFLAGS := -I ./inc
AM_CPPFLAGS += -I ${top_srcdir}/inc
AM_CPPFLAGS += -I ${top_srcdir}/
AM_CPPFLAGS += -I ${top_srcdir}/utils/inc
AM_CPPFLAGS += -I ${top_srcdir}/device/inc
AM_CPPFLAGS += -I ${top_srcdir}/session/inc
AM_CPPFLAGS += -I ${top_srcdir}/stream/inc
AM_CPPFLAGS += -I ${top_srcdir}/session/SessionAR/inc
AM_CPPFLAGS += -I ${top_srcdir}/plugins/PluginManager/inc
AM_CPPFLAGS += -I ${top_srcdir}/resource_manager/inc
AM_CPPFLAGS += -I ${top_srcdir}/context_manager/inc
AM_CPPFLAGS += -I ${top_srcdir}/plugins/vui_interface/api/vui-interface

plugin_manager_sources = ./src/PluginManager.cpp
else
AM_CPPFLAGS := -I ${top_srcdir}/plugins/PluginManager/inc/
AM_CPPFLAGS += -I ${top_srcdir}/inc
AM_CPPFLAGS += -I ${top_srcdir}
AM_CPPFLAGS += -I ${top_srcdir}/utils/inc
AM_CPPFLAGS += -I ${top_srcdir}/device/inc
AM_CPPFLAGS += -I ${top_srcdir}/session/inc
AM_CPPFLAGS += -I ${top_srcdir}/stream/inc
AM_CPPFLAGS += -I ${top_srcdir}/session/SessionAR/inc
AM_CPPFLAGS += -I ${top_srcdir}/plugins/PluginManager/inc
AM_CPPFLAGS += -I ${top_srcdir}/resource_manager/inc
AM_CPPFLAGS += -I ${top_srcdir}/context_manager/inc
AM_CPPFLAGS += -I ${top_srcdir}/plugins/vui_interface/api/vui-interface/
AM_CPPFLAGS += -I $(top_srcdir)/plugins/codecs
AM_CPPFLAGS += @KVH2XML_CFLAGS@

plugin_manager_sources = ${top_srcdir}/plugins/PluginManager/src/PluginManager.cpp
endif

library_includedir = $(includedir)/plugin_manager

lib_LTLIBRARIES     = libplugin_manager.la
libplugin_manager_la_SOURCES   = $(plugin_manager_sources)
libplugin_manager_la_LIBADD    = @GLIB_LIBS@ -lexpat
libplugin_manager_la_CPPFLAGS := $(AM_CPPFLAGS)
libplugin_manager_la_CPPFLAGS += -std=c++14 -fPIC
libplugin_manager_la_LDFLAGS   = --disable-shared -avoid-version
libplugin_manager_la_CPPFLAGS += @GLIB_CFLAGS@  -include glib.h
libplugin_manager_la_CPPFLAGS += -DACD_SM_FILEPATH=\"/etc/models/acd/\"
libplugin_manager_la_CPPFLAGS += -D__unused=__attribute__\(\(__unused__\)\) -DLINUX_ENABLED


if USE_SYSLOG
libplugin_manager_la_CPPFLAGS += -DPAL_USE_SYSLOG
endif

if BUILDSYSTEM_OPENWRT
libplugin_manager_la_LIBADD += -lglib-2.0 -llog
else
libplugin_manager_la_CPPFLAGS += -DPAL_USE_SYSLOG  -DATRACE_UNSUPPORTED -DCARD_STATE_UNSUPPORTED -DPAL_SIGNAL_HANDLER_UNSUPPORTED -DA2DP_SINK_SUPPORTED -DVUI_DMGR_AUDIO_UNSUPPORTED -DAUDIO_FEATURE_STATS_UNSUPPORTED
endif

if CUTILS_SUPPORTED
libplugin_manager_la_CPPFLAGS += -DPAL_CUTILS_SUPPORTED
libplugin_manager_la_LIBADD += -lcutils
endif

if USE_G_STR_FUNC
libplugin_manager_la_CPPFLAGS +=-Dstrlcpy=g_strlcpy -Dstrlcat=g_strlcat
endif
